# Site settings
title: Automated Testing Playbook
email: michael.bland@gsa.gov
description: >
  A set of principles, practices, idioms, and strategies pertaining to
  automated software testing and its adoption.
url: "http://18f.gsa.gov"
github_username:  18f

# Build settings
exclude:
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - go
  - vendor

theme: jekyll-uswds

# Author/Organization info to be displayed in the templates
author:
  name: 18F
  url: https://18f.gsa.gov

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /assets/img/18f-logo.svg
logoalt: 18f logo

# Navigation
# List links that should appear in the site sidebar here
navigation:

repos:
  - name: Automated Testing Playbook
    description: Main repository
    url: https://github.com/18F/automated-testing-playbook

google_analytics_ua: UA-48605964-19

styles:
  - /assets/css/main.css

defaults:
  - scope:
      path: ""
    values:
      layout: docs
      sidenav: primary
