# Site settings
title: 18F Automated Testing Playbook
email: michael.bland@gsa.gov
description: >
  A set of principles, practices, idioms, and strategies pertaining to
  automated software testing and its adoption.
url: "http://18f.gsa.gov"
github_username:  mbland

# Build settings
markdown: redcarpet
exclude:
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- go

permalink: pretty
highlighter: rouge

sass:
  style: :compressed

# DOCter bits after this

name: Automated Testing Playbook
subtitle:

# Author/Organization info to be displayed in the templates
author:
  name: 18F
  url: https://18f.gsa.gov

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /assets/img/18f-logo.png
logoalt: 18f logo

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Introduction
  url: index.html
  internal: true
- text: Automated Testing Roadmap
  url: roadmap/
  internal: true
- text: Principles, Practices and Idioms
  url: principles-practices-idioms/
  internal: true
- text: APIs and Legacy Systems
  url: apis-and-legacy-systems/
  internal: true
- text: Rapid Prototyping
  url: rapid-prototyping/
  internal: true
- text: Education and Advocacy
  url: education-and-advocacy/
  internal: true

repos:
- name: Automated Testing Playbook
  description: Main repository
  url: https://github.com/18F/automated-testing-playbook

google_analytics_ua: UA-48605964-19

back_link:
  url: "https://pages.18f.gov/guides/"
  text: Read more 18F Guides

defaults:
  -
    scope:
      path: ""
    values:
      layout: "guides_style_18f_default"
